export const livePlayerQuotaReset = [
  ["Billy Mattioli", 27],
  ["Bob Lipski", 34],
  ["Brandon Wills", 33],
  ["Chad Kelly", 23],
  ["Gary Neupauer", 17],
  ["Jay Thomas", 32],
  ["Jeff Hodorowski", 28],
  ["John Thomas", 27],
  ["Lou Belgio", 30],
  ["Marty Behm", 34],
  ["Mike Mahasky", 25],
  ["Mike Wills", 34],
  ["Rob Michaels", 23],
  ["Ryan Holthaus", 15],
  ["Scott Francis", 30],
  ["Scott Schifter", 15],
  ["AJ Kochanski", 26],
  ["Bob Ashworth", 21],
  ["Bogey", 22],
  ["Brett Sikora", 23],
  ["Brett Slocum", 25],
  ["Broj", 33],
  ["Chad DeBona", 30],
  ["Charlie Gelso", 29],
  ["Chris Jones", 29],
  ["Chris Sikora", 15],
  ["Chuck Brand", 31],
  ["Cooper Kelly", 30],
  ["Dave Straley", 30],
  ["Dave Yurko", 31],
  ["Derek Shurmanek", 26],
  ["Ethan Zawatski", 41],
  ["Jack Fenwick", 32],
  ["Jack Morris", 29],
  ["Jake Humphreys", 27],
  ["Jim Blinn", 34],
  ["Jim Fronzoni", 26],
  ["Joe Bevavino", 34],
  ["Joe Collini", 32],
  ["Joe Rubbico", 27],
  ["John Ashley", 32],
  ["Jonathon Wilson", 41],
  ["Matt Alfano", 19],
  ["Mike Aritz", 22],
  ["Mike Boland", 32],
  ["Mike Lipski", 23],
  ["Pat Murray", 26],
  ["Phil Lipski", 22],
  ["Ron Prokrinchak", 21],
  ["Tony Bevevino", 38],
  ["Travis Debona", 27]
] as const;

export const livePlayerQuotaResetMap = new Map<string, number>(livePlayerQuotaReset);
export const livePlayerQuotaResetVerificationNames = [
  "Gary Neupauer",
  "Chad Kelly",
  "Jeff Hodorowski",
  "Rob Michaels"
] as const;
export const livePlayerQuotaResetConfirmation = "RESET LIVE QUOTAS";
